### ISSUE TITLE
pangolin/gldraw.h build error

### ISSUE THREAD

**Issue by hamsal** [ankurhanda/SceneGraphRendering#1]
I get the following errors when trying to build

:~/SceneGraphRendering/build$ make -j
[  4%] [  8%] Building CXX object CMakeFiles/scenegraph.dir/src/GLGrid.cpp.o
Building CXX object CMakeFiles/scenegraph.dir/src/GLDynamicGrid.cpp.o
In file included from /home/hamsal/SceneGraphRendering/src/GLGrid.cpp:1:0:
/home/hamsal/SceneGraphRendering/include/SceneGraph/GLGrid.h:6:29: fatal error: pangolin/gldraw.h: No such file or directory
 #include <pangolin/gldraw.h>
                             ^
compilation terminated.
In file included from /home/hamsal/SceneGraphRendering/src/GLDynamicGrid.cpp:2:0:
/home/hamsal/SceneGraphRendering/include/SceneGraph/GLGrid.h:6:29: fatal error: pangolin/gldraw.h: No such file or directory
 #include <pangolin/gldraw.h>
                             ^
compilation terminated.
make[2]: **\* [CMakeFiles/scenegraph.dir/src/GLDynamicGrid.cpp.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
make[2]: **\* [CMakeFiles/scenegraph.dir/src/GLGrid.cpp.o] Error 1
make[1]: **\* [CMakeFiles/scenegraph.dir/all] Error 2
make: **\* [all] Error 2

**Comment by ankurhanda** [comment]
did you install pangolin with sudo make install? This file is there in the Pangolin-local https://github.com/ankurhanda/Pangolin-local/search?utf8=%E2%9C%93&q=gldraw.h

**Comment by howard-mahe** [comment]
I get the same errors. I installed pangolin with your Pangolin-local repo.

SceneGraphRendering is trying
`#include <pangolin/gldraw.h>`
but at your link https://github.com/ankurhanda/Pangolin-local/search?utf8=%E2%9C%93&q=gldraw.h we see the correct include should be
`#include <pangolin/gl/gldraw.h>`

At the moment, I fixed it by modifying all pangolin includes manually...
